# vim: ft=yaml:tw=2:sw=2
---
version: "3"

services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile_jenkins
      args:
        DOCKER_GID: ${DOCKER_GID}
    ports:
      - "8080:8080"
    volumes:
      - '/srv/jenkins/data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - net


networks:
  net:
...
